### ISSUE TITLE
Change request: Add additional course format settings

### ISSUE THREAD

**Issue by JorineKoenderman** [solin-repo/moodle-format_drip#6]
Tasks:

- [ ] Add course format setting: Exclude first X sections from drip (number; dropdown)
- [ ] Add course format setting: Duration drip section equal (Yes/No)
- [ ] Add course format setting: Fixed drip duration  (free number field) in days
- [ ] Add course format setting: Fields to set drip duration if duration not equal (free number fields for drip type Days) (date selection field for drip type Date); number of lines = number of sections- number from exclude first X sections from drip.
- [ ] Add course format setting: Show maximum number of future drips (number, dropdown)

**Description**
Expand the settings for this course format in the course settings:

Add possibility to set a fixed drip duration for a sequence of sections, but also exclude the first X number of sections from the drip. 

e.g.: Fixed drip duration =7 days, exclude first section from drip. This means the following will be set:

Drip topic 2: enrolment date + 7 days
Drip topic 3: enrolment date + 14 days
Drip topic 4: enrolment date + 21 days

Also add possibility to define number of future (unavailable) drips that are shown.

When you choose date ad a fixed drip duration, you need to define the date of the first drip section and the dates for the next sections are calculated based on the fixed drip duration.

The fixed drip duration will be defined in days.

Examples of the course format settings:
![Drip course format settings_examples](https://user-images.githubusercontent.com/60886688/97880074-003c2500-1d21-11eb-87f0-b80034e99d78.png)

**Comment by onno-schuit** [comment]
Removed most of the complex settings.
